---
- name: Get_Output
  hosts: jobiation_inventory
  gather_facts: no
  connection: local
  vars:
    ansible_command_timeout: 30
  tasks:
  - name: run_show_command
    cisco.ios.ios_command:
      commands: show run
    register: showrun
  - name: run_ios_commands
    cisco.ios.ios_command:
      commands:
        - config t
        - no interface loopback 10
        - end
        - write
    when: showrun is search("10.18.203.55")

  # - name: Gather all legacy facts
  #   cisco.ios.ios_facts:
  #     gather_subset: all
  #   register: ios_facts_out
  # - name: copy_output_to_file
  #   #copy: content="{{ ios_facts_out|json_query('ansible_facts') }}" dest="facts.json"
  #   copy: content="{{ ios_facts_out['ansible_facts']['ansible_net_filesystems_info']['bootflash:']['spacefree_kb'] }}" dest="{{ inventory_hostname }}.json"

  # - name: 
  #   ios_command:
  #     commands:
  #       - config t
  #       - interface loopback 10
  #       - ip address 10.18.203.55 255.255.255.255
  #       - end
  #       - write
  #   when: ios_facts_out['ansible_facts']['ansible_net_interfaces']['GigabitEthernet0/0/0']['macaddress'] == "2436.daf2.dc00"
