---
- name: Get_Output
  hosts: jobiation_inventory
  gather_facts: no
  connection: local
  vars:
    ansible_command_timeout: 30
  tasks:
# #################when show command#####################
  - name: run_show_command
    cisco.ios.ios_command:
      commands: show run
    register: showcmdoutput
  - name: copy_cmd_output_to_file
    copy: content="{{ showcmdoutput.stdout[0] }}" dest="{{ inventory_hostname }}.txt"
#   - name: run_ios_commands
#     cisco.ios.ios_command:
#       commands:
#         - config t
#         - end
#     when: showcmdoutput is search("10.18.203.55")

  # ###################when facts################3
  # - name: gather_facts
  #   cisco.ios.ios_facts:
  #   register: ios_facts
  # - name: copy_output_to_file
  #   copy: content="{{ ios_facts }}" dest="{{ inventory_hostname }}.json"
  # - name: run_ios_commands
  #   cisco.ios.ios_command:
  #     commands:
  #       - config t
  #       - end
  #   when: ios_facts['ansible_facts']['ansible_net_filesystems_info']['bootflash:']['spacefree_kb'] >= 1537809
