---
- name: jobiation_pb
  hosts: jobiation_inventory
  gather_facts: no
  vars:
   ansible_command_timeout: 30
  tasks:
   - name: gather_facts
     cisco.ios.ios_facts:
     register: jobiation_facts
   - name: copy_output_to_file
     copy: content="{{ jobiation_facts }}" dest="jobs/20221207_1658/facts/{{ inventory_hostname }}_facts.txt"
   - name: showrun
     cisco.ios.ios_command:
       commands: show running-config
     register: showrun
   - name: copy_output_to_file
     copy: content="{{ showrun.stdout[0] }}" dest="jobs/20221207_1658/showrun/{{ inventory_hostname }}_showrun.txt"
   - name: showver
     cisco.ios.ios_command:
       commands: show version
     register: showver
   - name: copy_output_to_file
     copy: content="{{ showver.stdout[0] }}" dest="jobs/20221207_1658/showver/{{ inventory_hostname }}_showver.txt"
