---
- name: temp_playbook
  hosts: legacyidfswitches
  gather_facts: no
  connection: local
  tasks:
   - name: temp_playbook
     ios_command:
      commands: show cdp neighbor
     register: output
   - name: show output
     debug:
      var: output.stdout
   - name: copy output to file
     copy: content="{{ output.stdout[0]}}" dest="./{{ inventory_hostname }}.txt"


#