# # Enable service account

# Set variables
    $selaclgrp = read-host "What is the name of the ACL group you want to deploy? Must match the aclgrp column value in devices.csv";
    $commands_file = $selaclgrp + ".txt";

    $ansible_server = "ansible";
    $devices_file = "..\devices.csv";
    $host_conditions_file = "..\host_conditions.ps1"; # Hosts conditions location
    $textedit_loc = "C:\Users\me\AppData\Local\Programs\Microsoft VS Code\Code.exe";
    $seconds = "30";

# Make sure user set the acl group in the hosts_conditons file
    write-host "";
    write-host "Check hosts_conditions.ps1 file before you continue. Press any key when ready.";
    write-host "";
    pause

# Make columns.ps1 and replacements.ps1 file
    $columns_file = ".\columns.ps1";
    $replacements_file = ".\replacements.ps1";
    $firstline = Get-Content "$devices_file" | select -First 1
    $flArray = $firstline.Split(",");
    out-file -filepath "$columns_file" -inputobject "#Autogenerated columns list" -encoding utf8;
    out-file -filepath "$replacements_file" -inputobject "#Autogenerated replacements list" -encoding utf8;
    foreach($column in $flArray)
    {
        out-file -filepath "$columns_file" -inputobject "`$$column = `$device.$column" -encoding utf8 -append;
        out-file -filepath "$replacements_file" -inputobject "if(`"`$$column`" -ne `"`"){((Get-Content -path `"`$current_dir\ansible_temp_task.yaml`") -replace '!$column',`$$column) | Set-Content -Path `"`$current_dir\ansible_temp_task.yaml`";}" -encoding utf8 -append;       
    }

# Import devices.csv and commands.txg
    $devices = Import-CSV $devices_file;
    $commands = Import-CSV $commands_file;

# Create a directory for the files
    $current_time=get-date -uformat %Y%m%d_%H%M%S
    $current_dir = ".\playbooks\$current_time";
    mkdir $current_dir;

# Create playbook file and add first line
    out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "---" -encoding utf8;

# Create hosts file
    copy-item "hosts_header" "$current_dir\hosts"

    out-file -filepath "$current_dir\hosts" -inputobject "   tempinventory:" -encoding utf8 -append;
    out-file -filepath "$current_dir\hosts" -inputobject "     hosts:" -encoding utf8 -append;

# Import Devices file
    foreach($device in $devices)
    {
        
    # Import host conditions and columns files
        . "$columns_file";
        . "$host_conditions_file";

    # Only perform commands on the specified ACL group
        if("$aclgrp" -eq "$selaclgrp"){}else{continue;}

    # Build playbook task for current device
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "- name: $devicename`_remote_task" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  hosts: $devicename" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  gather_facts: no" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  connection: local" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  vars:" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "    ansible_command_timeout: $seconds" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  tasks:" -encoding utf8 -append;

    # Build commands task for current device
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  - name: $devicename`_task" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "    ios_command:" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "      commands:" -encoding utf8 -append;

    # Add configure terminal command and remove the ACL form the firt interface
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - configure terminal" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - interface $aclint1" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - no ip access-group $aclname $aclint1dir" -encoding utf8 -append;

    # Remove ACL from second interface if aclint2 and aclint2dir are set
        if("$aclint2" -ne "" -AND "$aclint2dir" -ne "")
        {
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - interface $aclint2" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - no ip access-group $aclname $aclint2dir" -encoding utf8 -append;
        }

    # Remove the ACL
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - no ip access-list extended $aclname" -encoding utf8 -append;

    # Recreate the ACL
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - ip access-list extended $aclname" -encoding utf8 -append;

    # If the aclpreadd flag is set for current device, import the commands. Abort if commands file does not exist
        if("$aclpreadd" -eq "1")
        {
            $siteaddition_file = ".\additions\$devicename`_Pre.txt";

            if((test-path $siteaddition_file))
            {
                $siteaddcmds = Import-CSV $siteaddition_file;
                foreach($siteaddcmd in $siteaddcmds)
                {
                    out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - $($siteaddcmd.command)" -encoding utf8 -append;
                }

            }
            else
            {
                write-host "$devicename`_Pre.txt file does not exist. ABORTING!"
                pause
                exit;
            }
        }

    # Read ACL specific commands file and add to playbook
        foreach($command in $commands)
        {
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - $($command.command)" -encoding utf8 -append;
        }

    # If the aclpostadd flag is set for current device, import the commands. Abort if commands file does not exist
        if("$aclpostadd" -eq "1")
        {
            $siteaddition_file = ".\additions\$devicename`_Post.txt";

            if((test-path $siteaddition_file))
            {
                $siteaddcmds = Import-CSV $siteaddition_file;
                foreach($siteaddcmd in $siteaddcmds)
                {
                    out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - $($siteaddcmd.command)" -encoding utf8 -append;
                }

            }
            else
            {
                write-host "$devicename`_Post.txt file does not exist. ABORTING!"
                pause
                exit;
            }
        }

    # Add deny ip any any and apply to the first interface
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - $acllastcmd" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - interface $aclint1" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - ip access-group $aclname $aclint1dir" -encoding utf8 -append;

    # Add ACL to second interface if aclint2 and aclint2dir are set
        if("$aclint2" -ne "" -AND "$aclint2dir" -ne "")
        {
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - interface $aclint2" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - ip access-group $aclname $aclint2dir" -encoding utf8 -append;
        }

    # Write the config
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - end" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - write" -encoding utf8 -append;

    # End task for this device with ######################################
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "#" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "##########################################################################" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "#" -encoding utf8 -append;

    # Make replacements for variables
        . "$replacements_file";

    # Add hosts to host file
        out-file -filepath "$current_dir\hosts" -inputobject "       $devicename`:" -encoding utf8 -append;
        out-file -filepath "$current_dir\hosts" -inputobject "         ansible_host: $ip" -encoding utf8 -append;
    }

# Remove columns.ps1 and replacements.ps1
    remove-item $columns_file;
    remove-item $replacements_file;

# Check before executing
    write-host "";
    write-host "Check before executing."
    write-host "";
    start-process -filepath "$textedit_loc" -argumentlist "$current_dir\ansible_temp_task.yaml","$current_dir\hosts"
    pause

# Copy playbook and hosts file to Ansible server
    copy-item "$current_dir\hosts" "\\$ansible_server\ansiblerepo\hosts"
    copy-item "$current_dir\ansible_temp_task.yaml" "\\$ansible_server\ansiblerepo\playbooks\ansible_deploy_acl"

# # Run playbook an Ansible server
    plink "ansibleadmin@$ansible_server" "/var/ansiblerepo/playbooks/ansible_deploy_acl/ansible_temp_task.sh"

# Copy output back to current directory
    copy-item "\\$ansible_server\ansiblerepo\playbooks\ansible_deploy_acl\output\*" "$current_dir"

# # Disable service account
