---
- name: 
  hosts: Cockaponset
  gather_facts: no
  connection: local
  vars:
    ansible_command_timeout: 30
  tasks:
  - name:
    cli_command:
      command: 'write'
  - name:
    cli_command:
      command: 'reload in 720'
      check_all: True
      prompt:
        - 'Confirm'
      answer:
        - 'y'
  - name: 
    ios_command:
      commands:
        - config t
        - end
        - write
######################################################
