---
- name: Myrouter_pb
  hosts: Myrouter
  gather_facts: no
  vars:
    ansible_command_timeout: 30
  tasks:
  - name: Myrouter_commands
    ios_commands:
      commands:
        - config t
        - int loopback 5
        - ip address 10.18.255.100 255.255.255.0
        - hostname Myrouter
- name: Myrouter2_pb
  hosts: Myrouter2
  gather_facts: no
  vars:
    ansible_command_timeout: 30
  tasks:
  - name: Myrouter2_commands
    ios_commands:
      commands:
        - config t
        - int loopback 6
        - ip address 10.18.255.101 255.255.255.0
        - hostname Myrouter2
