---
- name: Jobiation1_pb
  hosts: Jobiation1
  gather_facts: no
  vars:
   ansible_command_timeout: 30
  tasks:
   - name: Jobiation1_commands
     ios_command:
      commands:
       - config t
       - interface loopback 20
       - ip address 10.18.255.120 255.255.255.255
       - end
       - write

###############################################################
