---
- name: Get_Configs
  hosts: tempinventory
  gather_facts: no
  connection: local
  tasks:
   - name: show_run
     ios_command:
      commands: show run
     register: output
   - name: show_output
     debug:
       var: output.stdout
   - name: copy_output_to_file
     copy: content="{{ output.stdout[0] }}" dest=/var/ansiblerepo/playbooks/device_backup/configs/{{ inventory_hostname }}_backup.txt



# ---
# - name: Get_Output
#   hosts: tempinventory
#   gather_facts: no
#   connection: local
#   vars:
#     ansible_command_timeout: 10
#   tasks:
#   - name: testdevice
#     ios_command:
#       commands: show run
#     register: output
#   - name: show_output
#     debug:
#       var: output.stdout
#   - name: copy_output_to_file
#     copy: content="{{ output.stdout[0] }}" dest="/etc/ansible/playbooks/ansible_get_output/output/{{ inventory_hostname }}.txt"

# ---
# - name: Upgrade 4507s
#   hosts: cat4507s
#   gather_facts: no
#   vars:
#     ansible_command_timeout: 1200
#   tasks:
#     - name: Copy IOS to switch
#       cli_command:
#         command: 'copy tftp://10.1.1.1/cat4500e-lanbasek9-mz.152-2.E8.bin bootflash'
#         check_all: true
#         prompt:
#           - 'Destination filename [cat4500e-lanbasek9-mz.152-2.E8.bin]?'
#         answer:
#           - 'cat4500e-lanbasek9-mz.152-2.E8.bin'          
#     - name: Chage boot system commands
#       ios_command:
#         commands:
#           - 'config t'
#           - 'no boot system bootflash:cat4500e-lanbasek9-mz.150-2.SG10.bin'
#           - 'boot system bootflash:cat4500e-lanbasek9-mz.152-2.E8.bin'
#           - 'boot system bootflash:cat4500e-lanbasek9-mz.150-2.SG10.bin'
#           - 'end'
#     - name: Reload at 20:00
#       cli_command:
#         command: 'reload at 20:00'
#         check_all: true
#         prompt:
#           - 'confirm'
#           - 'save'
#         answer:
#           - 'y' 
#           - 'y'
