# # Enable service account

# Set variables
    $ansible_server = "ansible";
    $devices_file = "..\devices.csv";
    $host_conditions_file = "..\host_conditions.ps1"; # Hosts conditions location
    $commands_file = "commands.txt";
    $textedit_loc = "C:\Users\me\AppData\Local\Programs\Microsoft VS Code\Code.exe";

# Make columns.ps1 and replacements.ps1 file
    $columns_file = ".\columns.ps1";
    $replacements_file = ".\replacements.ps1";
    $firstline = Get-Content "$devices_file" | select -First 1
    $flArray = $firstline.Split(",");
    out-file -filepath "$columns_file" -inputobject "#Autogenerated columns list" -encoding utf8;
    out-file -filepath "$replacements_file" -inputobject "#Autogenerated replacements list" -encoding utf8;
    foreach($column in $flArray)
    {
        out-file -filepath "$columns_file" -inputobject "`$$column = `$device.$column" -encoding utf8 -append;
        out-file -filepath "$replacements_file" -inputobject "if(`"`$$column`" -ne `"`"){((Get-Content -path `"`$current_dir\ansible_temp_task.yaml`") -replace '!$column',`$$column) | Set-Content -Path `"`$current_dir\ansible_temp_task.yaml`";}" -encoding utf8 -append;       
    }
    # Include '. "$columns_file";' in the devices loop;
    # Include '. "$replacements_file";' in the devices loop;
    # Include 'remove-item $columns_file;' before the pause
    # Include 'remove-item $replacements_file;' before the pause

# Import devices.csv and commands.txg
    $devices = Import-CSV $devices_file;
    $commands = Import-CSV $commands_file;

# Create a directory for the files
    $current_time=get-date -uformat %Y%m%d_%H%M%S
    $current_dir = ".\playbooks\$current_time";
    mkdir $current_dir;

# Prompt the user for a reload in 12 hourse and also ask if they want to override the default 30 command timeout
    $reload_bit = read-host "Press y to begin the playbook with a write and a reload in 720 or press the ENTER key to continue";
    $seconds = read-host "How many seconds command timeout? (Press ENTER for default 30 seconds)";
    if("$seconds" -eq ""){$seconds = "30";}

# Create playbooks
    out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "---" -encoding utf8;

# Create hosts file
    copy-item "hosts_header" "$current_dir\hosts"

    out-file -filepath "$current_dir\hosts" -inputobject "   tempinventory:" -encoding utf8 -append;
    out-file -filepath "$current_dir\hosts" -inputobject "     hosts:" -encoding utf8 -append;

    foreach($device in $devices)
    {
        . "$columns_file";
        . "$host_conditions_file";

        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "- name: $devicename_remote_task" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  hosts: $devicename" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  gather_facts: no" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  connection: local" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  vars:" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "    ansible_command_timeout: $seconds" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  tasks:" -encoding utf8 -append;

        if("$reload_bit" -eq "y")
        {
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  - name:" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "    cli_command:" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "      command: 'write'" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  - name:" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "    cli_command:" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "      command: 'reload in 720'" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "      check_all: True" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "      prompt:" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - 'Confirm'" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "      answer:" -encoding utf8 -append;
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - 'y'" -encoding utf8 -append;
        }

        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "  - name: $devicename_task" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "    ios_command:" -encoding utf8 -append;
        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "      commands:" -encoding utf8 -append;

        foreach($command in $commands)
        {
            out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "        - $($command.command)" -encoding utf8 -append;
        }

        out-file -filepath "$current_dir\ansible_temp_task.yaml" -inputobject "######################################################" -encoding utf8 -append;

        # Make replacements for variables
            . "$replacements_file";

        # Polulate Hosts file
            out-file -filepath "$current_dir\hosts" -inputobject "       $devicename`:" -encoding utf8 -append;
            out-file -filepath "$current_dir\hosts" -inputobject "         ansible_host: $ip" -encoding utf8 -append;
    }

# Remove columns.ps1 and replacements.ps1
    remove-item $columns_file;
    remove-item $replacements_file;

# Check before executing
    write-host "";
    write-host "Check playbook and host file before executing."
    write-host "";

    start-process -filepath "$textedit_loc" -argumentlist "$current_dir\ansible_temp_task.yaml","$current_dir\hosts"
    pause

# Copy playbook and hosts file to Ansible server
    copy-item "$current_dir\hosts" "\\$ansible_server\ansiblerepo\hosts"
    copy-item "$current_dir\ansible_temp_task.yaml" "\\$ansible_server\ansiblerepo\playbooks\ansible_command_send"

# # Run playbook an Ansible server
    plink "ansibleadmin@$ansible_server" "/var/ansiblerepo/playbooks/ansible_command_send/ansible_temp_task.sh"

# Copy output back to current directory
    copy-item "\\$ansible_server\ansiblerepo\playbooks\ansible_command_send\output\*" "$current_dir"

# # Pause so file copy has time to finish
#     start-sleep -s 10

# # Show playbook results
#     start-process -filepath "$textedit_loc" -argumentlist "$current_dir\playbook_results.txt"

# # Disable service account
