---
- name: disable_wifi
  hosts: disable_wifi_group
  gather_facts: no
  vars:
   ansible_command_timeout: 20
  connection: local
  tasks:
   - name: disable_wifi
     ios_command:
      commands:
       - 'config t'
       - 'int g0/2'
       - 'shut'