---
- name: jobiation_pb
  hosts: jobiation_inventory
  gather_facts: no
  vars:
   ansible_command_timeout: 30
  tasks:
   - name: Write
     cli_command:
       command: "write"
   - name: Reload
     cli_command:
       command: "reload in 60"
       check_all: True
       prompt:
         - "Confirm"
       answer:
         - "y"
   - name: jobiation_commands
     ios_command:
      commands:
       - config t
       - end
       - write
