---
- name: Jobiation1_pb
  hosts: Jobiation1
  gather_facts: no
  vars:
   ansible_command_timeout: 30
  tasks:
   - name: Jobiation1_commands
     ios_command:
      commands:
       - config t
       - logging host 10.18.101.86
       - logging facility local5
       - logging source-interface vlan 5
       - end
       - write

###############################################################
- name: Myrouter2_pb
  hosts: Myrouter2
  gather_facts: no
  vars:
   ansible_command_timeout: 30
  tasks:
   - name: Myrouter2_commands
     ios_command:
      commands:
       - config t
       - logging host 10.18.101.86
       - logging facility local5
       - logging source-interface vlan 6
       - end
       - write

###############################################################
