---
- name: CONDITIONALS SANDBOX
  hosts: localhost
  gather_facts: no    #<---Gather Facts Disabled
  tasks:

    - name: read the passwd file
      shell: cat /etc/ansible/mytextfile.txt
      register: regoutput

    - name: The string is in the file
      when: regoutput.stdout.find('My sub string') != -1
    #   debug: msg="String found in file."
      lineinfile:
       dest: /etc/ansible/temp.txt
       line: "File Status: String is in file."

    - name: Is the string is not in the file
      when: regoutput.stdout.find('My sub string') == -1
    #   debug: msg="String not found in file."
      lineinfile:
       dest: /etc/ansible/temp.txt
       line: "File Status: String is not in file."

# ---
# - name: GATHER FACTS FOR IOS
#   hosts: testgroup2
#   connection: network_cli
#   gather_facts: yes    #<---Gather Facts Disabled
#   tasks:
#     - name: GATHER FACTS FOR IOS IN A TASK
#       ios_facts:

#     - name: VIEW ALL ANSIBLE FACT KEYS
#       debug:
#         var: ansible_facts.keys()

#     - name: VIEW HOSTNAME
#       debug:
#         var: ansible_net_hostname

#     - name: VIEW OS VERSION
#       debug:
#         var: ansible_net_version

#     - name: VIEW IP ADDRESSES
#       debug:
#         var: ansible_net_all_ipv4_addresses



# - name: Temp Playbook
#   hosts: h10.1.1.1
#   gather_facts: yes
#   connection: local
#   vars:
#     ansible_command_timeout: 30
#   tasks:       
#     - name: temp task
#       ios_command:
#         commands:
#           - 'config t'
#           - 'int loopback46'


# - name: temp_playbook
#   hosts: legacyidfswitches
#   gather_facts: no
#   connection: local
#   tasks:
#    - name: temp_playbook
#      ios_command:
#       commands: show cdp neighbor
#      register: output
#    - name: show output
#      debug:
#       var: output.stdout
#    - name: copy output to file
#      copy: content="{{ output.stdout[0]}}" dest="./{{ inventory_hostname }}.txt"


# - name: Temp Playbook
#   hosts: testgroup2
#   gather_facts: no
#   connection: local
#   vars:
#     ansible_command_timeout: 30
#   tasks:       
#     - name: temp task
#       ios_command:
#         commands:
#           - 'show cdp neighbor'

# - name: Upgrade 4507s
#   hosts: cat4507s
#   gather_facts: no
#   vars:
#     ansible_command_timeout: 1200
#   tasks:
#     - name: Copy IOS to switch
#       cli_command:
#         command: 'copy tftp://10.1.1.1/cat4500e-lanbasek9-mz.152-2.E8.bin bootflash'
#         check_all: true
#         prompt:
#           - 'Destination filename [cat4500e-lanbasek9-mz.152-2.E8.bin]?'
#         answer:
#           - 'cat4500e-lanbasek9-mz.152-2.E8.bin'          
#     - name: Chage boot system commands
#       ios_command:
#         commands:
#           - 'config t'
#           - 'no boot system bootflash:cat4500e-lanbasek9-mz.150-2.SG10.bin'
#           - 'boot system bootflash:cat4500e-lanbasek9-mz.152-2.E8.bin'
#           - 'boot system bootflash:cat4500e-lanbasek9-mz.150-2.SG10.bin'
#           - 'end'
#     - name: Reload at 20:00
#       cli_command:
#         command: 'reload at 20:00'
#         check_all: true
#         prompt:
#           - 'confirm'
#           - 'save'
#         answer:
#           - 'y' 
#           - 'y'