---
- name: myrouter_remote_task
  hosts: myrouter
  gather_facts: no
  connection: local
  vars:
    ansible_command_timeout: 30
  tasks:
  - name: myrouter_task
    ios_command:
      commands:
        - configure terminal
        - interface Tunnel 13
        - no ip access-group TunnelACL out
        - no ip access-list extended TunnelACL
        - ip access-list extended TunnelACL
        - remark ...................... DHCP .......................
        - permit udp any any eq bootps
        - permit udp any any eq bootpc
        - remark ...................... DNS .......................
        - deny ip any any log
        - interface Tunnel 13
        - ip access-group TunnelACL out
        - end
        - write
#