---
- name: 
  hosts: myrouter
  gather_facts: no
  connection: local
  vars:
    ansible_command_timeout: 30
  tasks:
  - name: 
    ios_command:
      commands:
        - config t
        - banner motd #
        - ...............................................................
        - ..                                                           ..
        - ..                   W A R N I N G !!!                       ..
        - ..                 US GOVERNMENT SYSTEM                      ..
        - ..                                                           ..
        - ..                                                           ..
        - ..          Unauthorized access is prohibited by             ..
        - ..                   Public Law 99-474                       ..
        - ..       "The Computer Fraud and Abuse Act of 1986".         ..
        - ..            Use of this system constitutes                 ..
        - ..          CONSENT TO MONITORING AT ALL TIMES               ..
        - ..    and is not subject to ANY expectation of privacy.      ..
        - ..                                                           ..
        - ...............................................................
        - UnAuthorized Access Strictly Prohibited!!!!
        - #
        - end
        - write
######################################################
