---
- name: jobiation_pb
  hosts: jobiation_inventory
  gather_facts: no
  vars:
   ansible_command_timeout: 30
  tasks:
   - name: jobiation_commands
     ios_command:
      commands:
       - config t
       - end
       - write
